**Task1**

In [2]:
def length():
    """
    Converts length between meters and feet.

    Parameters:
        Takes user input for unit type and numeric value.

    Returns:
        Prints the converted value.
    """
    try:
        unit = input("Enter unit (m for meters, ft for feet): ").lower()
        value = float(input("Enter the value to convert: "))

        if unit == "m":
            result = value * 3.28084
            print("Meters to Feet:", result, "ft")

        elif unit == "ft":
            result = value / 3.28084
            print("Feet to Meters:", result, "m")

        else:
            print("Unsupported length unit.")

    except ValueError:
        print("Invalid input! Please enter a numeric value.")


def weight():
    """
    Converts weight between kilograms and pounds.

    Parameters:
        Takes user input for unit type and numeric value.

    Returns:
        Prints the converted value.
    """
    try:
        unit = input("Enter unit (kg for kilograms, lbs for pounds): ").lower()
        value = float(input("Enter the value to convert: "))

        if unit == "kg":
            result = value * 2.20462
            print("Kilograms to Pounds:", result, "lbs")

        elif unit == "lbs":
            result = value / 2.20462
            print("Pounds to Kilograms:", result, "kg")

        else:
            print("Unsupported weight unit.")

    except ValueError:
        print("Invalid input! Please enter a numeric value.")


def volume():
    """
    Converts volume between liters and gallons.

    Parameters:
        Takes user input for unit type and numeric value.

    Returns:
        Prints the converted value.
    """
    try:
        unit = input("Enter unit (L for liters, gal for gallons): ").lower()
        value = float(input("Enter the value to convert: "))

        if unit == "l":
            result = value * 0.264172
            print("Liters to Gallons:", result, "gal")

        elif unit == "gal":
            result = value / 0.264172
            print("Gallons to Liters:", result, "L")

        else:
            print("Unsupported volume unit.")

    except ValueError:
        print("Invalid input! Please enter a numeric value.")


def conv():
    """
    Main function that asks the user which type of conversion they want.

    Parameters:
        None

    Returns:
        Calls the appropriate conversion function.
    """
    conversion = input("Choose conversion type (length / weight / volume): ").lower()

    if conversion == "length":
        length()
    elif conversion == "weight":
        weight()
    elif conversion == "volume":
        volume()
    else:
        print("Invalid conversion type.")


# Run the program
conv()

Choose conversion type (length / weight / volume): length
Enter unit (m for meters, ft for feet): m
Enter the value to convert: 2
Meters to Feet: 6.56168 ft


**Task2**

In [ ]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
        numbers (list): list of numeric values

    Returns:
        float: sum of the numbers
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
        numbers (list): list of numeric values

    Returns:
        float: average of the numbers
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Finds the maximum value in a list.

    Parameters:
        numbers (list): list of numeric values

    Returns:
        float: maximum number
    """
    return max(numbers)


def find_min(numbers):
    """
    Finds the minimum value in a list.

    Parameters:
        numbers (list): list of numeric values

    Returns:
        float: minimum number
    """
    return min(numbers)


def main():
    """
    Main function to select an operation and perform it
    on a list of numbers entered by the user.
    """
    operation = input("Choose operation (sum / average / max / min): ").lower()

    try:
        numbers = input("Enter numbers separated by space: ").split()
        numbers = [float(num) for num in numbers]

        if len(numbers) == 0:
            print("Error: List cannot be empty.")
            return

        if operation == "sum":
            print("Sum =", find_sum(numbers))

        elif operation == "average":
            print("Average =", find_average(numbers))

        elif operation == "max":
            print("Maximum =", find_max(numbers))

        elif operation == "min":
            print("Minimum =", find_min(numbers))

        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numeric values.")


# Run program
main()

**4.2**


1

In [3]:
def extract_every_other(lst):
    """
    Returns every other element from the list starting from the first element.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element.
    """
    return lst[::2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print("Original list:", numbers)
print("Extracted list:", result)

Original list: [1, 2, 3, 4, 5, 6]
Extracted list: [1, 3, 5]


2

In [7]:
def get_sublist(lst):
    """
    Returns element from the list starting from the second element to 4the element

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing element from 2to4
    """
    return lst[2:5:1]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers)

print("Original list:", numbers)
print("Extracted list:", result)

Original list: [1, 2, 3, 4, 5, 6]
Extracted list: [3, 4, 5]


3

In [9]:
def reverse_list(lst):
    """
    Returns element from the list starting from the last element.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list reversing element.
    """
    return lst[::-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print("Original list:", numbers)
print("Extracted list:", result)

Original list: [1, 2, 3, 4, 5]
Extracted list: [5, 4, 3, 2, 1]


4

In [10]:
def remove_first_last(lst):
    """
    Returns element from the list starting from the second element to last element

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list excluding first and last element.
    """
    return lst[1:-1:1]


# Example
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print("Original list:", numbers)
print("Extracted list:", result)

Original list: [1, 2, 3, 4, 5]
Extracted list: [2, 3, 4]


5

In [17]:
def get_last_n(lst, n):
    """
    Returns the last n elements from the list.

    Parameters:
        lst (list): The input list
        n (int): number of elements to return from the end

    Returns:
        list: a new list containing the last n elements
    """
    return lst[-n:]


# Example
numbers = [1, 2, 3, 4, 5]
n = int(input("Enter the number of elements to get: "))

result = get_last_n(numbers, n)

print("Original list:", numbers)
print("Extracted list:", result)

Enter the number of elements to get: 2
Original list: [1, 2, 3, 4, 5]
Extracted list: [4, 5]


6

In [20]:
def get_first_n(lst,n):
    """
    Returns element from the list n
    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list including n
    """
    return lst[0:n:1]


# Example
numbers = [1, 2, 3, 4, 5]
n=int(input("Enter the number of n to get"))
result = get_first_n(numbers,n)

print("Original list:", numbers)
print("Extracted list:", result)

Enter the number of n to get2
Original list: [1, 2, 3, 4, 5]
Extracted list: [1, 2]


7

In [29]:
def reverse_skip(lst):
    """
    Returns element from the list starting from the last element.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list reversing element.
    """
    return lst[-2::-2]


# Example
numbers = [1, 2, 3, 4, 5,6]
result = reverse_skip(numbers)

print("Original list:", numbers)
print("Extracted list:", result)

Original list: [1, 2, 3, 4, 5, 6]
Extracted list: [5, 3, 1]


4.3


1

In [30]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
        lst (list): A nested list containing sublists.

    Returns:
        list: A single flattened list containing all elements.
    """
    flat_list = []

    for sublist in lst:
        for item in sublist:
            flat_list.append(item)

    return flat_list


# Example
numbers = [[1, 2], [3, 4], [5]]
result = flatten(numbers)

print("Original list:", numbers)
print("Flattened list:", result)

Original list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


2

In [31]:
def access_nested_element(lst, indices):
    """
    Returns a specific element from a nested list using given indices.

    Parameters:
        lst (list): The nested list.
        indices (list): A list of indices that specify the position.

    Returns:
        element: The value located at the specified indices.
    """
    element = lst
    for i in indices:
        element = element[i]
    return element


# Example
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(lst, indices)

print("Nested List:", lst)
print("Accessed Element:", result)

Nested List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Accessed Element: 6


In [32]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list.

    Parameters:
        lst (list): A nested list that may contain numbers or other lists.

    Returns:
        int/float: The total sum of all numeric elements in the nested list.
    """
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)   # recursive call
        else:
            total += item

    return total


# Example
numbers = [[1, 2], [3, [4, 5]], 6]

result = sum_nested(numbers)

print("Nested list:", numbers)
print("Sum of all elements:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): The nested list.
        elem: The element to remove.

    Returns:
        list: A new nested list with the element removed.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)

    return result


# Example
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

result = remove_element(lst, elem)

print("Original list:", lst)
print("Modified list:", result)

In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Parameters:
        lst (list): A nested list that may contain numbers or other lists.

    Returns:
        int/float: The maximum element in the nested list.
    """
    maximum = None

    for item in lst:
        if isinstance(item, list):
            value = find_max(item)   # recursive call
        else:
            value = item

        if maximum is None or value > maximum:
            maximum = value

    return maximum


# Example
numbers = [[1, 2], [3, [4, 5]], 6]

result = find_max(numbers)

print("Nested list:", numbers)
print("Maximum element:", result)

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
        lst (list): The nested list.
        elem: The element to count.

    Returns:
        int: Number of occurrences of elem in the nested list.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)   # recursive call
        elif item == elem:
            count += 1

    return count


# Example
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

result = count_occurrences(lst, elem)

print("Nested list:", lst)
print("Occurrences of", elem, ":", result)

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
        lst (list): A nested list that may contain lists within lists.

    Returns:
        list: A flattened list containing all elements.
    """
    flat_list = []

    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # recursive call
        else:
            flat_list.append(item)

    return flat_list


# Example
lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

result = deep_flatten(lst)

print("Original list:", lst)
print("Flattened list:", result)

In [ ]:
def average_nested(lst):
    """
    Returns the average of all numbers in a nested list.
    """
    total = 0
    count = 0

    for item in lst:
        if isinstance(item, list):
            for num in item:
                total += num
                count += 1
        else:
            total += item
            count += 1

    return total / count


# Example
lst = [[1, 2], [3, 4], [5, 6]]

result = average_nested(lst)

print("Nested list:", lst)
print("Average:", result)

Numpy

In [1]:
import numpy as np

# 1. Initialize an empty array with size 2x2
arr1 = np.empty((2,2))
print("Empty array (2x2):")
print(arr1)

# 2. Initialize an all one array with size 4x2
arr2 = np.ones((4,2))
print("\nOnes array (4x2):")
print(arr2)

# 3. Array filled with a specific value using np.full
arr3 = np.full((3,3), 7)
print("\nArray filled with 7:")
print(arr3)

# 4. Array of zeros with same shape as arr2
arr4 = np.zeros_like(arr2)
print("\nZeros like arr2:")
print(arr4)

# 5. Array of ones with same shape as arr2
arr5 = np.ones_like(arr2)
print("\nOnes like arr2:")
print(arr5)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\nList converted to numpy array:")
print(arr6)

Empty array (2x2):
[[8.98298962e-316 0.00000000e+000]
 [1.19831365e-304 4.02978715e-318]]

Ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like arr2:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones like arr2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

List converted to numpy array:
[1 2 3 4]


In [2]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10,50)
print("1.", arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3,3)
print("\n2.\n", arr2)

# 3. Create a 3x3 identity matrix
arr3 = np.eye(3)
print("\n3.\n", arr3)

# 4. Create a random array of size 30 and find mean
arr4 = np.random.random(30)
print("\n4. Mean:", arr4.mean())

# 5. Create a 10x10 random array and find min and max
arr5 = np.random.random((10,10))
print("\n5. Min:", arr5.min())
print("Max:", arr5.max())

# 6. Create zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\n6.", arr6)

# 7. Reverse the array
arr7 = np.array([1,2,0,0,4,0])
print("\n7.", arr7[::-1])

# 8. Create 2D array with 1 on border and 0 inside
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0
print("\n8.\n", arr8)

# 9. Create 8x8 checkerboard pattern
arr9 = np.zeros((8,8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9.\n", arr9)

1. [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2.
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3.
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean: 0.445823479128395

5. Min: 0.0010337651562992711
Max: 0.9963390618686085

6. [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. [0 4 0 0 2 1]

8.
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9.
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [3]:
import numpy as np

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
print("Addition:\n", x + y)

# 2. Subtract the two arrays
print("\nSubtraction:\n", x - y)

# 3. Multiply array with an integer
print("\nMultiply x by 2:\n", x * 2)

# 4. Square of each element
print("\nSquare of x:\n", x**2)

# 5. Dot products
print("\nDot product v and w:", np.dot(v,w))
print("Dot product x and v:\n", np.dot(x,v))
print("Dot product x and y:\n", np.dot(x,y))

# 6. Concatenation
print("\nConcatenate x and y along rows:")
print(np.concatenate((x,y), axis=0))

print("\nConcatenate v and w along columns:")
print(np.vstack((v,w)).T)

# 7. Concatenate x and v
try:
    print("\nConcatenate x and v:")
    print(np.concatenate((x,v)))
except Exception as e:
    print("Error:", e)

Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply x by 2:
 [[ 2  4]
 [ 6 10]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot product v and w: 219
Dot product x and v:
 [29 77]
Dot product x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [4]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Inverse of A
A_inv = np.linalg.inv(A)

# A * A^-1
result1 = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("\nA * A^-1 =\n", result1)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [5]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB =\n", AB)
print("\nBA =\n", BA)

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]


In [6]:
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T =\n", left)
print("\nB^T A^T =\n", right)

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]


In [7]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([[-1],
              [-3],
              [9]])

# Inverse of A
A_inv = np.linalg.inv(A)

# X = A^-1 B
X = np.dot(A_inv,B)

print("Solution (x,y,z):\n", X)

Solution (x,y,z):
 [[ 2.]
 [ 1.]
 [-2.]]


In [9]:
import numpy as np
import time

# --------------------------
# 1. Prepare large arrays/lists
# --------------------------
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

arr1 = np.array(list1)
arr2 = np.array(list2)

# --------------------------
# 1. Element-wise Addition
# --------------------------
# Python Lists
start = time.time()
list_add = [a+b for a,b in zip(list1,list2)]
list_time = time.time() - start

# NumPy Arrays
start = time.time()
arr_add = arr1 + arr2
numpy_time = time.time() - start

print("Element-wise Addition:")
print(f"Python List Time: {list_time:.5f}s, NumPy Time: {numpy_time:.5f}s")
print(f"Speed-up Factor (List / NumPy): {list_time / numpy_time:.2f}x\n")

# --------------------------
# 2. Element-wise Multiplication
# --------------------------
# Python Lists
start = time.time()
list_mul = [a*b for a,b in zip(list1,list2)]
list_time = time.time() - start

# NumPy Arrays
start = time.time()
arr_mul = arr1 * arr2
numpy_time = time.time() - start

print("Element-wise Multiplication:")
print(f"Python List Time: {list_time:.5f}s, NumPy Time: {numpy_time:.5f}s")
print(f"Speed-up Factor (List / NumPy): {list_time / numpy_time:.2f}x\n")

# --------------------------
# 3. Dot Product
# --------------------------
# Python Lists
start = time.time()
dot_list = sum(a*b for a,b in zip(list1,list2))
list_time = time.time() - start

# NumPy Arrays
start = time.time()
dot_arr = np.dot(arr1, arr2)
numpy_time = time.time() - start

print("Dot Product:")
print(f"Python List Time: {list_time:.5f}s, NumPy Time: {numpy_time:.5f}s")
print(f"Speed-up Factor (List / NumPy): {list_time / numpy_time:.2f}x\n")

# --------------------------
# 4. Matrix Multiplication
# --------------------------
mat_size = 300  # Reduced to 300x300 for faster demonstration
list_mat1 = [[j for j in range(mat_size)] for i in range(mat_size)]
list_mat2 = [[j for j in range(mat_size)] for i in range(mat_size)]

# Python Lists multiplication
start = time.time()
result_list = [[sum(list_mat1[i][k] * list_mat2[k][j] for k in range(mat_size))
                for j in range(mat_size)] for i in range(mat_size)]
list_time = time.time() - start

# NumPy Arrays multiplication
np_mat1 = np.array(list_mat1)
np_mat2 = np.array(list_mat2)

start = time.time()
np_result = np.dot(np_mat1, np_mat2)
numpy_time = time.time() - start

print("Matrix Multiplication:")
print(f"Python List Time: {list_time:.5f}s, NumPy Time: {numpy_time:.5f}s")
print(f"Speed-up Factor (List / NumPy): {list_time / numpy_time:.2f}x")

Element-wise Addition:
Python List Time: 0.08137s, NumPy Time: 0.00258s
Speed-up Factor (List / NumPy): 31.58x

Element-wise Multiplication:
Python List Time: 0.08458s, NumPy Time: 0.00439s
Speed-up Factor (List / NumPy): 19.28x

Dot Product:
Python List Time: 0.09018s, NumPy Time: 0.00191s
Speed-up Factor (List / NumPy): 47.14x

Matrix Multiplication:
Python List Time: 3.18423s, NumPy Time: 0.04115s
Speed-up Factor (List / NumPy): 77.38x
